### ISSUE TITLE
@mc on main function

### ISSUE THREAD

**Issue by ShalokShalom** [uniment/MethodChains.jl#2]
Hi :)

I think adding the @mc macro at the main function, could be an easy way to avoid typing it over and over again. 

Do you agree, or speaks anything against that?
Since you did not mention it in the README.
https://github.com/uniment/MethodChains.jl/blob/main/README.md

**Comment by mc** [comment]
I am not sure, I think you should be typing it repeatedly just to memorise it.

**Comment by ShalokShalom** [comment]
Why would I want to do that?

**Comment by George9000** [comment]
Why not just execute this line at the start of your script?
`MethodChains.init_repl()`

I'm using this in Emacs but it would work in any editor, such as SublimeText, that sends code to the terminal for execution.

**Comment by ShalokShalom** [comment]
Because.. I want the source code to be reproducible?
